### ISSUE TITLE
scdl: command not found

### ISSUE THREAD

**Issue by rinaldi6109** [flyingrub/scdl#271]
On a linux 18.04 machine, and after installing pip3 install scdl and invoking "scdl", I get:
`command not found
`

**Comment by flyingrub** [comment]
can you try `python3 -m scdl.scdl` ?

**Comment by rinaldi6109** [comment]
$ python3 -m scdl.scdl
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/antonio/.local/lib/python3.6/site-packages/scdl/scdl.py", line 73, in <module>
    from scdl import version, CLIENT_ID, ALT_CLIENT_ID
ImportError: cannot import name '__version__'

**Comment by flyingrub** [comment]
It seems there is an issue with how you installed scdl, I don't know how to help you with that... 😕

**Comment by useretail** [comment]
I also noticed this issue. After installation you can try to run a new instance of bash, and scdl will be there.

**Comment by rinaldi6109** [comment]
A new instance of bash?
does it suffice to open a new terminal window?
Thank you.

**Comment by useretail** [comment]
Yes, it did the trick for me. For some reason, command is not available immediately

**Comment by codydbgt** [comment]
this helped a lot thanks you should tell people using ssh to reopen there console or reconnect :)

**Comment by vgzhn** [comment]
This discussion saved me!

Can someone point me to something that explains what `python3 -m scdl.scdl` does? I've gotten really frustrated with scdl... resulting in `'scdl' is not recognized as an internal or external command,
operable program or batch file.`

I've been able to use `python3 -m scdl.scdl -l https://soundcloud.com/platform/dj-moma` with success, but I would like to be able to use the short notation in future :)

_lucky me only listened to the track after downloading it and decided it can be deleted again!_

**Comment by glowinthedarkninja** [comment]
vgzhn's comment on this discussion saved me.

I would also like to know more about what python3 -m scdl.scdl does.

Thanks for all your efforts and help everyone.

**Comment by jamesryan-dev** [comment]
```
╰─❯ scdl -me
zsh: command not found: scdl

╭─   ~
╰─❯ scdl https://soundcloud.com/sandervandoorn/sander-van-doorn-oliver-heldens-this-original-mixout-now
zsh: command not found: scdl

╭─   ~
╰─❯ python3 -m scdl.scdl
/opt/homebrew/opt/python@3.12/bin/python3.12: Error while finding module specification for 'scdl.scdl' (ModuleNotFoundError: No module named 'scdl')

╭─   ~
```

tried shutting my terminal down and openeing again btu still getting no luck with the command 

Also ran the suggested command here with this returned

**Comment by rohjli** [comment]
**Fix for scdl Not Found in zsh Shell After Installing with pipx**

If you’re using zsh and encountering a zsh: command not found: scdl error after installing scdl with pipx, it’s likely because the pipx binary path is not in your shell’s PATH. Here’s how to fix it:

1. Open your .zshrc file: `nano ~/.zshrc`
2. Add the following line to the end of the file: `export PATH="$PATH:$HOME/.local/bin"`
3. Save the file and reload your shell configuration: `source ~/.zshrc`
4. Verify the changes: `echo $PATH` You should now see /Users/your-username/.local/bin in the output.
5. Try running scdl again: The command should now be recognized and run correctly.

This fix ensures that the pipx installed binaries are available in your PATH in zsh.

This should be helpful for anyone who comes across the issue!

**Comment by styemmy** [comment]
had this issue suddenly after switching to fish, doing `fish_add_path ~/.local/bin/` worked for me
