### ISSUE TITLE
Using the -c option scdl download track that already exist instead of skipping them

### ISSUE THREAD

**Issue by flyingrub** [flyingrub/scdl#400]
`scdl -l https://soundcloud.com/flyingrub -p --flac -c`
When running this command scdl redownload tracks that already exist. Even though the `--overwrite` argument is not present.

**Comment by 7x11x13** [comment]
I can't reproduce this issue starting from nothing. But I believe the problem is caused by a different filename format between old and new versions, because I changed the default filename for tracks in playlists to include the playlist name and track number. If you change the playlist_name_format in scdl.cfg back to just {title} it should recognize files downloaded with the old name format.

**Comment by flyingrub** [comment]
This was the issue indeed, it was fixed by changing the config file.
