### ISSUE TITLE
Failed to create process

### ISSUE THREAD

**Issue by smithy285** [flyingrub/scdl#88]
Hello,
I am using Python version 3.5.0. I installed scdl using pip. I then edited C:\Users\Computer User\.config\scdl with notepad++ to include my token. Whenever I type scdl into cmd, I get the "failed to create process" error. I have tried running cmd as administrator.

**Comment by flyingrub** [comment]
I didn't tried python 3.5, but it's a weird error...

**Comment by smithy285** [comment]
Yeah, I've tried pretty much everything I can think off. Google doesn't come up with much either

**Comment by flyingrub** [comment]
Tried with 3.5, it's working fine. It seems related to windows.

**Comment by Darkefyre13** [comment]
@smithy285 when you installed python, did you do a system wide install or for your user only? because i had the same problem until i reinstalled it for me only

**Comment by smithy285** [comment]
@Darkefyre13 I've tried multiple times, I think I installed system wide

**Comment by Reverp** [comment]
This bug is caused by pip. Just had the same problem.

Go to the folder in which Python is installed. (C:\Users\Reverp\AppData\Local\Programs\Python\Python35-32 for me)

Open up scdl-script.py with some text editor and put quotes around your Python installation folder on the first line.

So
#!c:\users\reverp\appdata\local\programs\python\python35-32\python.exe

Becomes
#!"c:\users\reverp\appdata\local\programs\python\python35-32\python.exe"

This should work.
